services:
  db:
    image: postgres
    container_name: container_name
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: user_name
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_name
