import { RolesPermission } from 'src/roles_permissions/entities/roles_permission.entity';

export const rolesPermissionsSeeds: RolesPermission[] = [
  {
    id: 1,
    roleId: 1,
    permissionId: 1,
    createdAt: new Date(),
  },
  {
    id: 2,
    roleId: 1,
    permissionId: 2,
    createdAt: new Date(),
  },
  {
    id: 3,
    roleId: 1,
    permissionId: 3,
    createdAt: new Date(),
  },
  {
    id: 4,
    roleId: 1,
    permissionId: 4,
    createdAt: new Date(),
  },
  {
    id: 5,
    roleId: 1,
    permissionId: 5,
    createdAt: new Date(),
  },
  {
    id: 6,
    roleId: 1,
    permissionId: 6,
    createdAt: new Date(),
  },
  {
    id: 7,
    roleId: 1,
    permissionId: 7,
    createdAt: new Date(),
  },
  {
    id: 8,
    roleId: 1,
    permissionId: 8,
    createdAt: new Date(),
  },
  {
    id: 9,
    roleId: 1,
    permissionId: 9,
    createdAt: new Date(),
  },
  {
    id: 10,
    roleId: 1,
    permissionId: 10,
    createdAt: new Date(),
  },
  {
    id: 11,
    roleId: 1,
    permissionId: 11,
    createdAt: new Date(),
  },
  {
    id: 12,
    roleId: 1,
    permissionId: 12,
    createdAt: new Date(),
  },
  {
    id: 13,
    roleId: 1,
    permissionId: 13,
    createdAt: new Date(),
  },
  {
    id: 14,
    roleId: 1,
    permissionId: 14,
    createdAt: new Date(),
  },
  {
    id: 15,
    roleId: 1,
    permissionId: 15,
    createdAt: new Date(),
  },
  {
    id: 16,
    roleId: 1,
    permissionId: 16,
    createdAt: new Date(),
  },
  {
    id: 17,
    roleId: 1,
    permissionId: 17,
    createdAt: new Date(),
  },
  {
    id: 18,
    roleId: 1,
    permissionId: 18,
    createdAt: new Date(),
  },
  {
    id: 19,
    roleId: 1,
    permissionId: 19,
    createdAt: new Date(),
  },
  {
    id: 20,
    roleId: 1,
    permissionId: 20,
    createdAt: new Date(),
  },
  {
    id: 21,
    roleId: 1,
    permissionId: 21,
    createdAt: new Date(),
  },
  {
    id: 22,
    roleId: 1,
    permissionId: 22,
    createdAt: new Date(),
  },
  {
    id: 23,
    roleId: 1,
    permissionId: 23,
    createdAt: new Date(),
  },
  {
    id: 24,
    roleId: 1,
    permissionId: 24,
    createdAt: new Date(),
  },
  {
    id: 25,
    roleId: 2,
    permissionId: 6,
    createdAt: new Date(),
  },
  {
    id: 26,
    roleId: 2,
    permissionId: 7,
    createdAt: new Date(),
  },
  {
    id: 27,
    roleId: 2,
    permissionId: 8,
    createdAt: new Date(),
  },
  {
    id: 28,
    roleId: 2,
    permissionId: 9,
    createdAt: new Date(),
  },
  {
    id: 29,
    roleId: 3,
    permissionId: 6,
    createdAt: new Date(),
  },
  {
    id: 30,
    roleId: 3,
    permissionId: 9,
    createdAt: new Date(),
  },
];
